### PR TITLE
count correctly all buttons even if not mapped

### PR DESCRIPTION
**Pull request by nadenislamarre**

### CODE REVIEW

**Comment by garbear** [comment]
I have no style requirements here. Does this fix an issue? (It's not apparent in the description.) If yes I'll merge immediately.

**Comment by garbear** [comment]
Merging, as it's apparent from the code that this probably fixes an issue.

**Comment by nadenislamarre** [comment]
hi. very good news. im away 2 days, but then i can reread and help you. you can find me on the batocera.linux discord too if needed. i need a computer to read correctly.

**Comment by nadenislamarre** [comment]
for this one, it is easy. it was looping from misc to max. but in practice, some pad includes buttons under misc. there is no reason to not start at 0 and to start a misc by the way. from 0 to max is the good way.

**Comment by garbear** [comment]
sounds good, thanks for the explanation. I reviewed all the open PRs, ran them on my Steam Deck with the udev driver, and also ran them through chat-gpt for additional inspection. On udev on the Steam Deck for at least one controller it looks like buttons/axes that didn't work before, work now. Thanks!

**Comment by garbear** [comment]
@nadenislamarre All your patches are in peripheral.joystick as of version 21.1.18 for Omega, and version 20.1.18 for Nexus. If you update to these versions you can drop Batocera's patches.

**Pull request merged**
