### PR TITLE
Adding linux driver buttonmap for 8BitDo M30

### PR DESCRIPTION
**Pull request by mintsoft**

### CODE REVIEW

**Comment by garbear** [comment]
Sorry, I missed this PR. It doesn't look like axis 4 is used, should this appear in the config?

**Comment by garbear** [comment]
You can test which axis is axis 4 in the "Ignore Input" dialog on the right of the controller config dialog.

**Comment by mintsoft** [comment]
I'll check on Axis 4; it's a kind of weird pad that uses both buttons and axes simultaneously for things. I'll verify what is correct in a min

**Comment by mintsoft** [comment]
Just checked and the additional axis are used when the shoulder buttons are pressed, but there is no analogue nature to them, they go from -32k when not pressed to +32k when pressed, so I would prefer to map the buttons 9/10 (or 8/9 if 0 indexed) than use the axes in this situation?

**Comment by garbear** [comment]
> they go from -32k when not pressed to +32k when pressed

When a button is analog but only goes between discrete values, I call them "discrete analog" buttons. You can also see that Kodi detected axis 4 went from -32k (normalized to -1) to 32k (normalized to 1), which is a center of -1 and a range of 2:

```xml
<axis index="4" center="-1" range="2" />
```

When a button sends both analog and digital presses, Kodi appears to get two inputs very close together, which I call "rapid input" and drop the second input, in this case the axes.

So Kodi handles all these quirks just fine, but we might as well use the digital ones.

The analog axes should probably be marked as "ignored", which you can see how it's done with the PS4 controller: https://github.com/xbmc/peripheral.joystick/blob/Omega/peripheral.joystick/resources/buttonmaps/xml/linux/Sony_Interactive_Entertainment_Wireless_Controller_13b_8a.xml#L8-L9. You can use the ignore input dialog to generate these lines, then re-map and copy/paste the ignored axes into the XML.

**Comment by mintsoft** [comment]
I've made that change; the controller physically looks and acts like a SEGA Saturn controller, is it preferred to map onto the Saturn profile (like the 8Bitdo_NES30_GamePad_16b_8a maps onto SNES) or is the generic one better?

**Comment by garbear** [comment]
Yes, can you map the profile that looks most like the controller? You'll see in the Peripherals list that it shows up as the controller you've mapped if it's the only buttonmap. The Saturn icon will also be shown in the in-game dialogs.

**Comment by mintsoft** [comment]
Done and done

**Comment by garbear** [comment]
Looks good. Can you squash the commits and title the commit "`[Linux] Add buttonmap for ...`"?

If you're not familiar with git, just do a soft-reset to master (`git reset ad6bab7dd70c1bf51551e3d8a4082a724ca3f771`) then you'll see that your xml is an uncommited file. So just add it and create a new commit message. Then force-push to GH (`git push -f origin mintsoft-patch-1`).

**Comment by mintsoft** [comment]
Done

**Comment by garbear** [comment]
I got this in a new release for both Omega and Nexus, just in case you're on the older branch.

**Pull request merged**
