### PR TITLE
Remove pcre dependency

### PR DESCRIPTION
**Pull request by Paxxi**
With only a simple regex used there's no real reason to depend
on pcre instead of the regex support in c++

compile tested on windows, not runtime tested.

### CODE REVIEW

**Comment by garbear** [comment]
#37 - android doesn't play well with std::regex. Is this still the case?

**Comment by garbear** [comment]
and doesn't pcre fail to build on aarch64? do we even need to build this add-on for android?

**Comment by Paxxi** [comment]
I'm not entirely sure, there's been some improvements but we're still using one of the worse stdlibs available so it would likely require testing if that's still true.

**Comment by garbear** [comment]
> do we even need to build this add-on for android?

Turns out even though this add-on doesn't scan for joysticks on android, it's still needed for mapping android controllers to kodi actions

Does this add-on still fail to compile for aarch64?

**Comment by wsnipex** [comment]
>Does this add-on still fail to compile for aarch64?
yes, first pcre fails(which I could fix), then you require SDL, which is not defined as dependency here, nor is built in depends on any platform but darwin.

**Comment by garbear** [comment]
SDL can be dropped entirely. The SDL driver is ported from kodi's old joystick code and was only used as a backup to the linux (and now udev) drivers

**Comment by garbear** [comment]
https://github.com/kodi-game/peripheral.joystick/pull/56 drops SDL

**Comment by Rechi** [comment]
@garbear can this be reconsidered?
Android and Raspberry Pi use a newer compiler since it was last tried, which supports `std::regex` correctly.
I successfully compile tested it for android, ios, osx & windows (desktop & uwp).

**Comment by garbear** [comment]
The regex code path isn't hit on Android, so I think building was the only concern. It should be fine.

**Pull request merged**
