### PR TITLE
[darwinEmbedded] Controller support for Extended and Micro gamepads

### PR DESCRIPTION
**Pull request by fuzzard**
Apple supports gamepads with 2 specific button layous.
Extended is a traditional xbox style controller (14button, 2 axis)
Micro is similar to an NES controller (6 button - dpad + 2 buttons)

MicroGamepad can potentially handle motion, but i'll go with the easy assumption for now.

No need to merge this as yet, obviously still working on the rest of the pieces. Figure i'll just get this in place whilst i remember

### CODE REVIEW

**Comment by garbear** [comment]
Did you generate these by hand or using the controller configuration utility?

**Comment by fuzzard** [comment]
Definitely by hand, haha, didn't even know there was a utility

**Comment by garbear** [comment]
https://kodi.wiki/view/HOW-TO:Configure_controllers. See if it yields any differences

**Comment by fuzzard** [comment]
Went through a few iterations, but the extended controller layout is now fully tested and functional. I may look to add some other controller types (eg. Steelseries Nimbus), but i'll need some logging from Kambala to get that tested with. This can be done later.
Micro layout is entirely untested, as im personally only aware of 1 micro gamecontroller (Apple TV siri remote), and i dont have the tvos input handling in a state to function (complete rewrite required potentially)

**Comment by garbear** [comment]
Cool, ready to merge? Closing and re-opening to trigger CI.

**Comment by fuzzard** [comment]
Ready for merge when ci is happy

**Comment by garbear** [comment]
Failing on iOS-armv7 packaging. Got any ideas? @Rechi can you tell what's wrong?

**Comment by fuzzard** [comment]
It's a pipeline issue, there are no longer armv7 builds in master. Alwin has a PR open for removing that platform pipeline in master builds

**Comment by garbear** [comment]
K, not like these XMLs are tested in the pipeline anyway

**Pull request merged**
