### PR TITLE
FIX: include cpack

### PR DESCRIPTION
**Pull request by koying**

### CODE REVIEW

**Comment by Rechi** [comment]
Why is this needed?

**Comment by notspiff** [comment]
it  is needed to generates zip files.

**Comment by Rechi** [comment]
Sure, but why is it needed in this CMakeLists.txt? It doesn't generate any zip file.

**Comment by notspiff** [comment]
ït does. 'make addon-package'.

**Comment by Rechi** [comment]
Again, the CMakeLists.txt from this repo doesn't do anything about packaging. `addon-package` is defined in the kodi repo.

**Comment by notspiff** [comment]
it *is* needed. it has to go after all calls to build_addon. it cannot be included in the generic macros as there are repos spitting out multiple add-ons.

**Comment by koying** [comment]
No clue about the inners, tbh, but factually/empirically, 'make addon-package' choke on each and every addon not including cpack.
Did half-a-dozen similar PR yesterday ;)

**Comment by Rechi** [comment]
Tested it myself and you are right, doesn't work without it.
I trust @notspiff if he says it can't be included in the generic addon macros.

**Pull request merged**
