### PR TITLE
[fix] windows build failures

### PR DESCRIPTION
**Pull request by Rechi**
- TCHAR & TEXT identifiers don't start with an underscore
- updated to C++ based addon interface for window

@garbear @AlwinEsch FYI

### CODE REVIEW

**Comment by Rechi** [comment]
@AlwinEsch can this be merged or is there something wrong?

**Comment by AlwinEsch** [comment]
Is in, was waiting for @garbear :)

**Comment by Rechi** [comment]
That was only to inform him about the wrong identifiers he introduced.

**Comment by garbear** [comment]
I believe the underscores were for a macro that evaluated to `wchar_t` on unicode systems and `char` on non-unicode systems. I'll try compiling this on Windows 7 and see if it still works.

**Comment by garbear** [comment]
Confirmed that this builds in my Windows 7 VM. I'll try actual hardware when I'm back from vacation.

**Pull request merged**
