### PR TITLE
[Matrix] update CMakeLists.txt to 3.5, cleanups, copyright year increase, icon add

### PR DESCRIPTION
**Pull request by AlwinEsch**
For unknown reason was this missing on Matrix version where required for https://github.com/xbmc/xbmc/pull/16458

Has compared Leia vs. Matrix here, except the build system and version was this the only difference between both.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Contains now the same changes as #176 with this:
Bildschirmfoto von 2020-01-31 22-39-47

**Review by garbear — APPROVED** [review]
Huh. Looks good.

**Comment by MilhouseVH** [comment]
Getting this build failure since #175/#177 (but guessing it's this PR): http://ix.io/29d1

Building 464ada2b7e14fc7d582f17f8dc61e1ab33b15e71 against latest Kodi master (ef7cd84c883c940df1e304fb16bcf87a007cc593)

(Ignore the name of the peripheral.joystick directory in the build log - it's the latest Matrix version as I repackage the Matrix tarball and overwrite the currently configured tarball version which is currently Leia in the LE tree).

**Comment by MilhouseVH** [comment]
Hmmm... maybe something has gone horribly wrong with my builds... I seem to have picked up a version of CMakeLists.txt with:
```
cmake_minimum_required(VERSION 3.1)
```
so not entirely sure what version I've downloaded - investigating, as probably PEBKAC, will update soon...!

**Comment by MilhouseVH** [comment]
Sorry, false alarm - it's a bug in my build script which meant I hadn't deleted the old `peripheral.joystick` build directory (the version prior to these new updates) so it continued to build the old 3.1 version. Sigh :frowning:

**Pull request merged**
