### PR TITLE
[android] Add buttonmap for back button in Android TV Remote Control

### PR DESCRIPTION
**Pull request by garbear**
## Motivation and Context
Report: https://forum.kodi.tv/showthread.php?tid=308480

## How Has This Been Tested?
Tested on Shield TV.

## Screenshots (if appropriate):
Android TV Remote Control:
android tv remote control

### CODE REVIEW

**Comment by CiNcH83** [comment]
BACK button is again non-functional after installing a nightly build. After disabling the Joystick add-on, the BACK button starts to work again.

**Comment by garbear** [comment]
Thanks for reporting, I found the issue. Will fix this week.

**Comment by garbear** [comment]
Issue is fixed, we just need a new buttonmap for Android TV Remote Control. Can you make one?

**Comment by CiNcH83** [comment]
Sure. Never done one and no clue what is wrong with the one in this PR, but I am sure I can figure this out :) .

**Comment by garbear** [comment]
Ha, forgot I did this last time. Go to controller configuration utility in settings and map the back button to back on the Kodi and remote profile (from Get More link)

**Comment by CiNcH83** [comment]
This is what came out:

```<?xml version="1.0" ?>
<buttonmap>
    <device name="virtual-remote" provider="android" buttoncount="18">
        <controller id="game.controller.default">
            <feature name="back" button="6" />
        </controller>
        <controller id="game.controller.remote">
            <feature name="back" button="6" />
        </controller>
    </device>
</buttonmap>
```

However, Back again isn't the Back I am expecting. In fullscreen video it seems to bring up player controls. That whole stuff is just beyond me... Guess this mapping has to do with joystick.xml? Back button should do the equivalent to keyboard backspace IMHO.

**Pull request merged**
