### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-peripherals/peripheral-joystick/) for Kodi add-ons: peripherals/peripheral.joystick.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by garbear** [comment]
@gade01 Should this go to Nexus?

**Comment by AlwinEsch** [comment]
> @gade01 Should this go to Nexus?

Firstly no, as Kodi Matrix currently the released one. After Kodi Nexus becomes his first relases (Alpha/Beta...) can we swap to it.

After I'm done all the addons for Nexus, I look to make short update commits/requests to take from Matrix to Nexus.
And also in future from time to time to have equal.

**Comment by gade01** [comment]
@garbear 
Excactly as @AlwinEsch wrote. We use Matrix branch as long as that's the latest official Kodi version.

**Review by gade01 — APPROVED** [review]

**Comment by garbear** [comment]
> I look to make short update commits/requests to take from Matrix to Nexus.

Sounds like a lot of work, but I guess it's required with our branching strategy used for version compatibility.

**Pull request merged**
